apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-acl-config
  namespace: emqx
data:
  acl.conf: |
    {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
    {allow, {ipaddr, "127.0.0.1"}, subscribe, ["$SYS/#", "#"]}.
    {allow, all, subscribe, ["foobar/#"]}.
    {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
    {deny, all}.
---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx/emqx-enterprise:5.10.2
  config:
    data: |
      authorization.sources = [{
        type = file
        enable = true
        path = "/opt/emqx/etc/acl.conf"
      }]
      license.key = evaluation
  coreTemplate:
    spec:
      extraVolumes:
        - name: acl-config
          configMap:
            name: emqx-acl-config
      extraVolumeMounts:
        - name: acl-config
          mountPath: /opt/emqx/etc/acl.conf
          subPath: acl.conf
          readOnly: true
  replicantTemplate:
    spec:
      extraVolumes:
        - name: acl-config
          configMap:
            name: emqx-acl-config
      extraVolumeMounts:
        - name: acl-config
          mountPath: /opt/emqx/etc/acl.conf
          subPath: acl.conf
          readOnly: true
